### ISSUE TITLE
Proposal for SignStory?

### ISSUE THREAD

**Issue by Kofola45cz** [maximuslotro/SignStory#3]
@maximuslotro Hello dev,
- Wouldn't it be better if SignStory functions could be changed using a GUI like SignPicture.
- because using commands seems to me not clear, and at the same time it is quite problematic for me to understand how the part with selecting "pages" works, because I can't understand how to describe the .txt so that it works.

- At the same time I discovered a problem with recording text after entering the loud_text command , when the chat closes. But by having the player click upload .txt - the ESC Menu opens, and the game GUI from Minecraft remains foreground even during Windows Explorer
Edit: - yeah, now I see that overlapping GUI with windows explorer is probably a longer problem from SignPicture... mostly one didn't use this, but with SignStory one will use it much more than with SignPicture, where so many people didn't have to use it because they had to use the url image from the internet because of the servers
- Can't close the GUI Up window until the player returns to minecraft to close it.
![Snímek obrazovky 2022-04-07 201941](https://user-images.githubusercontent.com/22054484/162271051-1f29b4c6-97dc-4d4f-8a9a-cc12072dff10.png)

- I could only paste the first word of the .txt on the sign - I personally don't understand the formatting of the text
[test.txt](https://github.com/maximuslotro/SignStory/files/8445536/test.txt)

- Next I'd just like to say that while laying the sign, how is the flashing text on the top left or the loading GUI window, etc.
So it probably wouldn't be a bad idea to separate the translation, as in practice the word "Image" and "Text" change depending on usage.
SignPicture: _Place Sign and Apply Image_
SignStory: _Place Sign and Apply text_

**Comment by maximuslotro** [comment]
Thanks for the questions, let me answer them one by one.

1. Making a Gui for the SignStory functions is on my list of things to add/tweak.
2. I'm sorry that it is a bit confusing. I need to expand on the explanation of what pages are. Basically a page is as many words as the mod can fit into a 60 character string with cutting any words on 15 character intervals.
3. The Upload/selection box staying on top of the select file dialog was always a issue with the signpicture mod, i will look into it and see if i can fix it from staying on top.
4. ~~Same as question 3?~~ There is a bug with Signstory, that if the text ends on the fourth line of a sign, the mod will fail to load the file, and the select gui stays open. Tested your text file and found that it was the case for me. 
5. The next release changes how text is parsed and planed onto a sign, but in the meantime could you send a picture of what the text on the sign looks like after placing it. Tne next update, v1.0.3, will fix some of the issues that happened when i opened your text file.
6. So far the only modifying of the mod i have done is adding under-the-hood changes to allow each to work  without interfering with the other's functionality, I can see how having the messages say images instead of text and vice versa is an issue, I will work on that in the next release.

Thanks for your time. :)

**Comment by maximuslotro** [comment]
With version v1.0.3 release
1. Added to to-do list
2. Just load a text file normally, all a page is, is a 60 character long string broken up into 4, 15 character long lines that mod can place on a sign, so one page is one sign.
3. Fixed with v1.0.3
4. ^
5. ^
6. Added a separate file selection gui for text file in v1.0.3 

Does this update solve your problems?

**Comment by Kofola45cz** [comment]
@maximuslotro Thank.
- Now I understand "page" , it's actually "4 lines = 1 page = 1 sign" in .txt :-)
- So besides the GUI, see the picture, could you make a text department?
(
 see mention: Next I'd just like to say that while laying the sign, ....
 SignPicture: Place Sign and Apply Image
 SignStory: Place Sign and Apply text
![Bez názvu](https://user-images.githubusercontent.com/22054484/162414914-710653eb-3e48-4b99-b868-c5093feaa8db.png)
)

**Comment by maximuslotro** [comment]
@Kofola45cz 
Glad you understand what a page is.
And for it showing the wrong text in the upper corner, i guess i didn't test for that. I think i have a setting turned off, that when on, it will show that. I will fix that in the next update sometime in the new few days. Thanks :)

**Comment by Kofola45cz** [comment]
> @Kofola45cz Jsem rád, že chápeš, co je stránka. A protože se v horním rohu zobrazuje nesprávný text, myslím, že jsem to netestoval. Myslím, že mám vypnuté nastavení, že když je zapnuté, zobrazí se to. Opravím to v příští aktualizaci někdy v nových dnech. Dík :)

ok

**Comment by Kofola45cz** [comment]
@maximuslotro ok :)

**Comment by Kofola45cz** [comment]
@maximuslotro 
ok, I just tested SignStory v1.0.3
- I have SignStory on
-error message when using /SignStory select_page :
_No Text Loaded
Please Enable SignStory First!_
-wouldn't be better?:
_No Text Loaded
Use first (/SignStory load_text) to Load Text First_
 
- error loading from lang:
![Snímek obrazovky 2022-04-08 204602](https://user-images.githubusercontent.com/22054484/162502830-5ab1b494-32fb-4c0a-b746-549eec433db7.png)

- when the GUI file loader opens, but I accidentally click "back to game", the GUI window closes (it's no longer there after opening ESC), and the louding_text command doesn't work at that point.
Even after reloading the world or switching the mode to SignPicture and back.
- there are probably multiple ways to cause this bug and I'm not even sure if you can duplicate it too.

- Otherwise, just an idea. Maybe it would be a good idea to add a bit to the info: "text in .txt - 4 lines = 1 page = 1 sign" ?
Maybe this will help someone better understand how to write to .txt
 ;)
 
 - Otherwise, I have almost finished the translation for the newer versions of SignStory, but due to changes I will wait for a while before I put a "Pull Request" to merge. ;)

**Comment by maximuslotro** [comment]
Thanks i will look into the language bug, and an explanation of how text should be formatted, and change the loading message. Also do you mean the  "back to game" button on the minecraft pause menu?

**Comment by Kofola45cz** [comment]
@maximuslotro yes, "back to game" in ESC Menu

**Comment by maximuslotro** [comment]
Ive added an example of how text is parsed and how you don't have to manually edit your text. [https://github.com/maximuslotro/SignStory/blob/main/src/main/resources/Example_Text.txt](https://github.com/maximuslotro/SignStory/blob/main/src/main/resources/Example_Text.txt ). Will push an update soon that will fix all the items in the In Progress tab [https://github.com/maximuslotro/SignStory/projects](https://github.com/maximuslotro/SignStory/projects/1)

**Comment by maximuslotro** [comment]
This Issue has been going on for a long time, through 2 versions, and keeps getting new stuff added to it. For the sake of keeping issue numbers clean, I'm closing this issue. If you have anymore questions or issues with future versions, please feel free to open an new issue. Have a good day. :)
