### ISSUE TITLE
visual error during placing, etc.

### ISSUE THREAD

**Issue by Kofola45cz** [maximuslotro/SignStory#4]
SignStory mod v1.0.4 - test
- Yeah, I've seen this bug in 1.0.3 but I forgot to mention it.
- the text is loaded -> on first placement we see the visual placement -> on second placement, the second page however the visual disappears -> but the text on placement of course works.
![2022-04-14_10 06 10](https://user-images.githubusercontent.com/22054484/163342080-208d1116-9fd5-4e21-bf24-4c88494dbf51.png)
![2022-04-14_10 06 15](https://user-images.githubusercontent.com/22054484/163342089-4358d228-b2d8-4a90-951f-400193a622bd.png)
![2022-04-14_10 07 20](https://user-images.githubusercontent.com/22054484/163342092-855e4ea9-d948-4873-9efa-1c5b04d2d035.png)

-------

- When I disconnected that world and reconnected, I tried what happens when I use it: /SignStory select_page # -> it caused that the text was not loaded anymore but it still remembered the number of pages, even the possibility to change pages, but of course the back text could not be put, because of course the player must first use loud_text to make it work.
- But of course it's not important... :)
![2022-04-14_10 13 10](https://user-images.githubusercontent.com/22054484/163344198-7af42e91-397f-45cc-8fe2-9b036e6ee909.png)

-------

I would suggest with this error that the error message when entering /SignStory select_page # should have two messages, when either SignStory On and when SignStory Off.
![Snímek obrazovky 2022-04-14 102227](https://user-images.githubusercontent.com/22054484/163345557-99e32c38-5ddb-4ffc-93ca-2daa4a61ca80.png)

/SignStory select_page # + SignStory Off:
![Snímek obrazovky 2022-04-14 102416](https://user-images.githubusercontent.com/22054484/163345489-dc37a952-a093-4795-ac6c-4d71414b7014.png)
/SignStory select_page # + SignStory On:
![Snímek obrazovky 2022-04-14 102807](https://user-images.githubusercontent.com/22054484/163345667-49435c51-1f9c-4255-9494-703deb1993cb.png)
- it makes more sense to me this way, error messages.

-------

- When I was translating lang, the new parts:
- just a question, wouldn't this sentence make more sense like this?:
signstory.command.text.set.fail.char.after=Please remove these characters from the text file and try loading the file again.
- Of course just my opinion, no need to change it right away, I just thought about it a bit.. :)

-------

- Otherwise I guess the text from "Example_Text.txt" will be implemented in the game or somewhere as info in the future and possibly multiple translations?

- Yeah, sorry for the long message again. 😅

**Comment by maximuslotro** [comment]
Love the Questions. :smiley:
Let me answer each point at a time.

1. Ive never experienced the sign disappearing after a successful place before. Will look into it.
2. I see, the text and page number still being loaded by the mod, but exiting and rejoining a world caused the mod to exit placing mode and the only way to enable place mode for text is to reload the text. Will need to change that.
3. Yes, your way makes more sense, will change the messaging.
4. Well when the mod parses a text file, to allow for end of paragraph spaces on signs, i used a dummy character, previously only the & symbol, which is why one couldn't load a file containing one, as it would mess-up the parsing process. With the v1.0.4 updates I added additional dummy parsing characters % $ @ { } as well as the original &. If the & symbol is present in a text file, it will try to use another of characters for the parsing dummy, but it all 6 characters are present in the text file, it will fail to parse the file. So to fix a file that has all the characters in it, you only need to "remove one of these characters from your text file" which is why you can still have some of the characters present but not all. Ex "What the %&$}@" would work but "Why you $}@&{%" will fail.
5. Another thing to add to the to-do list.

Hope you understand point 4. I will look into the bugs, and push some language changes, please check the change i made. :grin:

Looking through a translator, i think `Odeberte prosím jeden z těchto znaků zcela z textového souboru a zkuste soubor načíst znovu.` looks right for point 4, but i can't read it and I don't know if is how you'd say it.

We just love sending long messages don't we? :joy:

**Comment by Kofola45cz** [comment]
@maximuslotro 
   4. So I made a tiny little adjustment for that sentence, though it probably wouldn't have mattered in the final. :)
    -  so I don't have anything to translate or edit at the moment, I guess it doesn't get any better. :D

**Comment by maximuslotro** [comment]
“Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.”

― Antoine de Saint-Exupéry,

**Comment by maximuslotro** [comment]
Did v1.0.5 fix the bug "Potentially Fixed a bug where the sign render would disappear after placing a sign. (to-do:[12](https://github.com/maximuslotro/SignStory/projects/1#card-80660587)) https://github.com/maximuslotro/SignStory/issues/4"?
If it did, i will close this Issue. 😃
