### ISSUE TITLE
Just a question of future versions of Minecraft

### ISSUE THREAD

**Issue by Kofola45cz** [maximuslotro/SignStory#7]
I just have a question, do you plan to port it in the future after debugging and tweaking...etc. 
SignStory port to newer versions of Minecraft?
Of course I'm just asking, I know that porting a mod is not easy.

**Comment by maximuslotro** [comment]
The base code of the mod is running the signpicture mod code. It had code versions 1.7.10-1.12.2. theoretically it wouldn't be that hard to port this mod the versions between this, but making a version for 1.13.2+ would be a big undertaking, since i would have to port both mods essentially to the new versions. I might make a port someday to 1.16.5+ if i have the time, but that would be a big undertaking, and i don't have the time or skills with modern forge versions rn.

**Comment by maximuslotro** [comment]
If there's a specific version between 1.7.10 and 1.12.2 that you'd be interested to see this mod ported to, it'd be possible for me to do it over the course of a week or so. But pointing it to a version after 1.12.2, that would be a large undertaking. 1.13 changed a lot of code that's why many forge mods fail to have a version after 1.12.2.

**Comment by Kofola45cz** [comment]
I understand. :)
